model_name_or_path: Qwen/Qwen3.5-27B
model_revision: fc05daec18b0a78c049392ed2e771dde82bdf654
dtype: bfloat16
attn_implementation: flash_attention_2
dataset_num_proc: 16
remove_unused_columns: false
dataset_train_split: train
dataset_test_split: validation
dataloader_num_workers: 8
train_sampling_strategy: group_by_length
tf32: true
num_train_epochs: 3
warmup_ratio: 0.03
optim: adamw_torch_fused
lr_scheduler_type: cosine
seed: 42
logging_steps: 10
eval_strategy: steps
eval_steps: 0.25
save_strategy: steps
save_steps: 0.2
save_total_limit: 2
save_only_model: true
bf16: true
fp16: false
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
report_to: none
max_length: 2368
output_dir: sft-output/full_ft_qwen3_5_27b
run_name: full_ft_qwen3_5_27b
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 32
learning_rate: 1.0e-05
weight_decay: 0.05
deepspeed: configs/deepspeed_zero3.json
