model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
model_revision: cc594898137f460bfe9f0759e9844b3ce807cfb5
dtype: bfloat16
attn_implementation: flash_attention_2
dataset_num_proc: 16
remove_unused_columns: false
dataset_train_split: train
dataset_test_split: validation
dataloader_num_workers: 8
tf32: true
num_train_epochs: 3
warmup_ratio: 0.03
optim: adamw_torch_fused
lr_scheduler_type: cosine
seed: 42
logging_steps: 10
eval_strategy: steps
eval_steps: 100
save_strategy: steps
save_steps: 500
save_total_limit: 2
bf16: true
fp16: false
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
report_to: none
max_length: 2752
output_dir: ../sft-output/full_ft_qwen2_5_vl_7b
run_name: full_ft_qwen2_5_vl_7b
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 32
learning_rate: 2.0e-05
weight_decay: 0.05
deepspeed: configs/deepspeed_zero2.json
