model_name_or_path: Qwen/Qwen3.5-27B
model_revision: fc05daec18b0a78c049392ed2e771dde82bdf654
dtype: bfloat16
attn_implementation: flash_attention_2
dataset_num_proc: 16
remove_unused_columns: false
val_size: 0.02
num_train_epochs: 3
warmup_ratio: 0.03
optim: adamw_torch
lr_scheduler_type: cosine
seed: 42
logging_steps: 10
eval_strategy: steps
eval_steps: 100
save_strategy: steps
save_steps: 500
save_total_limit: 2
bf16: true
fp16: false
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
report_to: none
max_length: 2368
output_dir: ../sft-output/lora_ft_qwen3_5_27b
run_name: lora_ft_qwen3_5_27b
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 0.0002
weight_decay: 0.01
use_peft: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj
