model_name_or_path: "Qwen/Qwen3.5-9B"
model_revision: "c202236235762e1c871ad0ccb60c8ee5ba337b9a"
dtype: "bfloat16"
attn_implementation: "flash_attention_2"

max_length: 11120
dataset_num_proc: 4 #или 8
# dataset_kwargs:
#   skip_prepare_dataset: true
remove_unused_columns: false

output_dir: "../qwen3-vl-sft-output/lora_ft"
num_train_epochs: 3

per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 2.0e-4
warmup_ratio: 0.03
weight_decay: 0.01
optim: "adamw_torch"
lr_scheduler_type: "cosine"

logging_steps: 10
eval_strategy: "no"
save_strategy: "steps"
save_steps: 100
save_total_limit: 2

bf16: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

use_peft: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - "q_proj"
  - "k_proj"
  - "v_proj"
  - "o_proj"
  - "gate_proj"
  - "up_proj"
  - "down_proj"
